apiVersion: v1
kind: Pod
metadata:
  name: timestamper
  namespace: staging
spec:
  containers:
  - env:
    - name: PGDB
      value: {{ .Values.postgres.dbname }}
    - name: PGHOST
      valueFrom:
        secretKeyRef:
          key: PGHOST
          name: timestamper-postgresql-secret
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          key: PGPASSWORD
          name: timestamper-postgresql-secret
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          key: PGUSER
          name: timestamper-postgresql-secret
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: Always
    name: timestamper
    resources:
      limits:
        cpu: 20m
        memory: 20Mi
      requests:
        cpu: 10m
        memory: 10Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      runAsGroup: 1
      runAsNonRoot: true
      runAsUser: 1000
