apiVersion: v1
kind: Secret
metadata:
  name: timestamper-postgresql-secret
  namespace: staging
type: Opaque
data:
  PGHOST: {{ .Values.postgres.host | b64enc }}
  PGUSER: {{ .Values.postgres.user | b64enc }}
  PGPASSWORD: {{ .Values.postgres.password | b64enc }}
