apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timestamper
  namespace: argocd-system
spec:
  project: default
  source:
    repoURL: git@github.com:davidumea/timestamper.git
    targetRevision: HEAD
    path: timestamper
    helm:
      valuesObject:
        postgres:
          host: set-me
          user: set-me
          password: set-me
          dbname: set-me
        image:
          repository: set-me
          tag: set-me
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
